services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "90:90"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - paxos_net
    depends_on:
      - backend
      
  backend:
    build: .
    environment:
      - REDIS_HOST=redis
      - PORT=5000
      - NODE_ID=node1
    networks:
      - paxos_net
    depends_on:
      - redis
      
  redis:
    image: redis:latest
    networks:
      - paxos_net
    
  paxos:
    build: .
    command: python paxos_service.py
    environment:
      - REDIS_HOST=redis
      - NODE_ID=node1
      - PYTHONUNBUFFERED=1
    networks:
      - paxos_net
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  sender:
    build: .
    command: python sender.py
    environment:
      - REDIS_HOST=redis
      - NODE_ID=node1
    networks:
      - paxos_net
    depends_on:
      - redis

networks:
  paxos_net:
    driver: bridge 